### ISSUE TITLE
Lookup provider from SNS request information

### ISSUE THREAD

**Issue by chambridge** [project-koku/masu#67]
When an SNS update comes in we will get the S3 bucket name and cost usage definition key. We need to be able to look up the provider from the S3 bucket name so we can trigger the download and processing appropriately.

If the provider is not found within the in memory data, assume the data is stale and call to obtain the updated data. If the provider is still not found log the info as an error.

______
Associated with: https://github.com/project-koku/masu/issues/7

**Comment by dccurtis** [comment]
The situation of having stale provider data will not occur with the current implementation.  We are creating a new orchestrator each time we download/process.  During orchestrator initialization a new list of accounts are created each time.

This may be a problem if we ever move to a model where the orchestrator lives forever and handles requests as they come in.  I'm closing this for now since there is no issue with the current implementation.
